export const coreDetails = [
    {
        id: 1,
        name: "Purvashi Shah",
        image: "/core/puru.jpg",
        position: "Chairperson",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 2,
        name: "Yogesh Yadav",
        image: "/core/yogesh.jpg",
        position:"Vice-Chairperson",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 3,
        name: "Khushi Nikhade",
        image: "/core/Khushiinikhade.jpg",
        position:"Secretary",
        instagram: "",
        linkedIn:"https://www.linkedin.com/in/khushii-nikhade-a6473ab7",
    },
    {
        id: 4,
        name: "Ishal Raut",
        image: "/core/IshalRaut.jpeg",
        position: "Event Manager",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 5,
        name: "Abhisekh Mishra",
        image: "/core/abhisekh.jpg",
        position: "Sponsership Head",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 6,
        name: "Hitanshu Bhudev",
        image: "/core/HitanshuBudhdev.jpeg",
        position: "Treasurer",
        instagram: "https://instagram.com/1heet2?igshid=YTQwZjQ0NmI0OA==",
        linkedIn:"https://www.linkedin.com/in/hitanshu-budhdev-5b9622282",
    },
    {
        id: 7,
        name: "Atharva Vartak",
        image: "/core/AtharvaVartak.jpg",
        position: "Technical Head",
        instagram: "https://instagram.com/0xatharv?igshid=YTQwZjQ0NmI0OA==",
        linkedIn:"https://www.linkedin.com/in/atharva-vartak-69066127a",
    },
    {
        id: 8,
        name: "Anooshka Mahajan",
        image: "/core/anooshka.png",
        position: "Publication Head",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 9,
        name: "Hricha Mehra",
        image: "/core/hricha.png",
        position: "Webmaster",
        instagram: "",
        linkedIn:"",
    },
    {
        id: 10,
        name: "Shlok Mishra",
        image: "/core/ShlokMishra.jpg",
        position: "Event Coordinator",
        instagram: "https://instagram.com/shlxkm?igshid=NzZlODBkYWE4Ng==",
        linkedIn:"https://www.linkedin.com/in/slych",
    }
]